---
- name: ensure launch agents directory
  file:
    path: ~/Library/LaunchAgents
    state: directory
    recurse: yes

- include_tasks: "darwin/env.yml"
- include_tasks: "darwin/syncthing.yml"
- include_tasks: "darwin/unbound.yml"
