---
- import_tasks: "lang/asdf.yml"
- import_tasks: "lang/elixir.yml"
- import_tasks: "lang/erlang.yml"
- import_tasks: "lang/golang.yml"
- import_tasks: "lang/helm.yml"
- import_tasks: "lang/kubectl.yml"
- import_tasks: "lang/minikube.yml"
- import_tasks: "lang/nodejs.yml"
- import_tasks: "lang/python2.yml"
- import_tasks: "lang/python3.yml"
- import_tasks: "lang/ruby.yml"
- import_tasks: "lang/rust.yml"
