---

# dotfiles.yml

dots:
  - ~/.aria2
  - ~/.emacs.d
  - ~/.ssh

archlinux_dots:
  - ~/.xmonad

links:
  - source: ~/.dotfiles/etc/aria2.conf
    dest: ~/.aria2/aria2.conf

  - source: ~/.dotfiles/etc/gitconfig
    dest: ~/.gitconfig

  - source: ~/.dotfiles/etc/hgrc
    dest: ~/.hgrc

  - source: ~/.dotfiles/etc/profile
    dest: ~/.profile

  - source: ~/.dotfiles/emacs/init.el
    dest: ~/.emacs.d/init.el

  - source: ~/.dotfiles/ssh/config
    dest: ~/.ssh/config

  - source: ~/.dotfiles/etc/tmux.conf
    dest: ~/.tmux.conf

  - source: ~/.dotfiles/zsh/zshrc
    dest: ~/.zshrc

  - source: ~/.dotfiles/zsh/zprofile
    dest: ~/.zprofile

darwin_links:
  - source: ~/.dotfiles/etc/amethyst
    dest: ~/.amethyst

archlinux_links:
  - source: ~/.dotfiles/etc/Xresources
    dest: ~/.Xresources

  - source: ~/.dotfiles/etc/xmonad.hs
    dest: ~/.xmonad/xmonad.hs

  - source: ~/.dotfiles/etc/xprofile
    dest: ~/.xprofile
