---
- name: install rust plugin via asdf
  git:
    repo: https://github.com/code-lever/asdf-rust
    dest: ~/.asdf/plugins/rust

- name: install rust {{rust_version}} via asdf
  command: ~/.asdf/bin/asdf install rust {{rust_version}}
  args:
    creates: ~/.asdf/installs/rust/{{rust_version}}

- name: set rust {{rust_version}} as default
  command: ~/.asdf/bin/asdf global rust {{rust_version}}
  changed_when: false

- name: create rust source directory
  file: path=~/.local/src/rust state=directory recurse=yes

- name: extract rust source for {{rust_version}}
  shell: |
    mkdir -p ~/.local/src/rust/rustc-{{rust_version}} &&
    curl https://static.rust-lang.org/dist/rustc-{{rust_version}}-src.tar.gz |
    tar -xvzf - --strip-components 1 -C ~/.local/src/rust/rustc-{{rust_version}}
  args:
    warn: no
    creates: "~/.local/src/rust/rustc-{{rust_version}}"

- name: install rust packages
  command: ~/.asdf/installs/rust/{{rust_version}}/bin/cargo install {{item}}
  args:
    creates: ~/.cargo/bin/{{item}}
  with_items: "{{rust_packages}}"
  environment:
    PATH: "{{ansible_env.HOME}}/.asdf/installs/rust/{{rust_version}}/bin:{{ansible_env.PATH}}"

- name: update rust {{rust_version}} shims
  command: ~/.asdf/bin/asdf reshim rust
  changed_when: false
