allowed = [
  "developer.mozilla.org",
  "docs.python.org",
  "pkg.go.dev",
  "docs.rs",
  "docs.ruby-lang.org",
  "nodejs.org",
  "npmjs.com",
  "pypi.org",
  "crates.io",
  "github.com",
  "raw.githubusercontent.com",
  "github.io",
  "docs.github.com",
  "git-scm.com",
  "nixos.org",
  "nix.dev",
  "wiki.nixos.org",
  "search.nixos.org",
]
