---
- name: install docker service
  become: yes
  pacman: name=docker state=latest
  notify:
    - restart docker systemd service

- name: enable docker service
  systemd:
    name: "docker"
    enabled: yes
    user: yes
    state: started
