---
# Some brew packages (e.g. scala) required Java to be installed.
- name: install java
  homebrew_cask: name=java state=present

- include_tasks: "darwin/brew.yml"
- include_tasks: "darwin/cask.yml"
