---

# packages/archlinux/pacman

- name: upgrade pacman packages
  become: yes
  pacman: upgrade=yes

# packages/acrhlinux/aur_pacaur

- name: upgrade pacaur packages
  pacaur: upgrade=yes

# packages/darwin/brew

- name: upgrade homebrew packages
  homebrew: upgrade_all=yes

# services/archlinux/docker

- name: restart docker systemd service
  systemd:
    name: "docker"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/mpd

- name: restart mpd systemd service
  systemd:
    name: "mpd"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/nfs

- name: restart nfs-server systemd service
  become: yes
  systemd:
    name: "nfs-server"
    daemon_reload: yes
    state: restarted

# services/archlinux/redshift

- name: restart redshift systemd service
  systemd:
    name: "redshift"
    user: yes
    daemon_reload: yes
    state: restarted

# services/archlinux/unbound

- name: restart unbound systemd service
  become: yes
  systemd:
    name: "unbound"
    daemon_reload: yes
    state: restarted

# services/darwin/env

- name: unload environment launchd service
  command: launchctl unload ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

- name: load environment launchd service
  command: launchctl load ~/Library/LaunchAgents/th.in.grid.env.plist
  ignore_errors: yes

# services/darwin/ethereum

- name: unload ethereum launchd service
  command: launchctl unload ~/Library/LaunchAgents/org.ethereum.ethereum.plist
  ignore_errors: yes

- name: load ethereum launchd service
  command: launchctl load ~/Library/LaunchAgents/org.ethereum.ethereum.plist
  ignore_errors: yes

# services/darwin/unbound

- name: unload unbound launchd service
  command: launchctl unload ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes

- name: load unbound launchd service
  command: launchctl load ~/Library/LaunchAgents/net.unbound.unbound.plist
  ignore_errors: yes
